# mujoco simulation step rate [hz]
rate_ros: 1000.0

# robot state publish rate [hz]
rate_state: 500.0

# frame id used in the published state header
model_urdf: ""
model_mjcf: ""
model_frame_id: "base_link"

# publish joint states / enable viewer
prog_viewer: true
prog_rviz: true
